-- 샘플 문항 20개
INSERT INTO QUESTION VALUES(1, 1, 2023, 1, '정규화의 목적으로 옳지 않은 것은?', '정규화는 데이터 중복을 제거하고 데이터 무결성을 보장하기 위한 과정입니다.', 3, 'APPROVED', 1, SYSTIMESTAMP);
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 1, 1, '데이터 중복을 최소화한다', 'N');
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 1, 2, '데이터 무결성을 보장한다', 'N');
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 1, 3, '데이터 처리 속도를 최대화한다', 'Y');
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 1, 4, '이상 현상을 제거한다', 'N');

INSERT INTO QUESTION VALUES(2, 1, 2023, 1, '제1정규형(1NF)의 조건은?', '제1정규형은 모든 속성이 원자값을 가져야 합니다.', 2, 'APPROVED', 1, SYSTIMESTAMP);
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 2, 1, '모든 속성이 원자값을 가진다', 'Y');
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 2, 2, '부분 함수 종속이 제거되어야 한다', 'N');
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 2, 3, '이행 함수 종속이 제거되어야 한다', 'N');
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 2, 4, '다치 종속이 제거되어야 한다', 'N');

INSERT INTO QUESTION VALUES(3, 2, 2023, 1, 'SELECT문에서 중복된 행을 제거하는 키워드는?', 'DISTINCT는 중복 행을 제거합니다.', 1, 'APPROVED', 1, SYSTIMESTAMP);
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 3, 1, 'UNIQUE', 'N');
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 3, 2, 'DISTINCT', 'Y');
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 3, 3, 'REMOVE', 'N');
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 3, 4, 'DELETE', 'N');

INSERT INTO QUESTION VALUES(4, 2, 2023, 1, '공통 속성이 없어도 사용할 수 있는 JOIN은?', 'CROSS JOIN은 카티션 프로덕트를 생성합니다.', 3, 'APPROVED', 1, SYSTIMESTAMP);
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 4, 1, 'INNER JOIN', 'N');
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 4, 2, 'OUTER JOIN', 'N');
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 4, 3, 'CROSS JOIN', 'Y');
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 4, 4, 'NATURAL JOIN', 'N');

INSERT INTO QUESTION VALUES(5, 3, 2023, 1, '스택(Stack)의 특징으로 옳은 것은?', '스택은 LIFO 구조입니다.', 2, 'APPROVED', 1, SYSTIMESTAMP);
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 5, 1, 'FIFO 구조이다', 'N');
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 5, 2, 'LIFO 구조이다', 'Y');
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 5, 3, '임의 접근이 가능하다', 'N');
INSERT INTO Q_OPTION VALUES(SEQ_OPTION.NEXTVAL, 5, 4, '우선순위 큐이다', 'N');

-- 시험지 생성
INSERT INTO EXAM_PAPER VALUES(1, '2023년 1회 정보처리산업기사', 'G', 2023, 1, 90, SYSTIMESTAMP);
INSERT INTO PAPER_Q VALUES(1, 1, 1);
INSERT INTO PAPER_Q VALUES(1, 2, 2);
INSERT INTO PAPER_Q VALUES(1, 3, 3);
INSERT INTO PAPER_Q VALUES(1, 4, 4);
INSERT INTO PAPER_Q VALUES(1, 5, 5);

INSERT INTO EXAM_PAPER VALUES(2, '2024년 1회 정보처리산업기사', 'G', 2024, 1, 90, SYSTIMESTAMP);
INSERT INTO PAPER_Q VALUES(2, 1, 1);
INSERT INTO PAPER_Q VALUES(2, 2, 2);
INSERT INTO PAPER_Q VALUES(2, 3, 3);

COMMIT;
