-- ============================================
-- 정보처리산업기사 CBT 시스템 DDL (Oracle)
-- ============================================

-- 시퀀스
CREATE SEQUENCE SEQ_USER START WITH 1000;
CREATE SEQUENCE SEQ_SUBJECT START WITH 1;
CREATE SEQUENCE SEQ_UNIT START WITH 1;
CREATE SEQUENCE SEQ_TAG START WITH 1;
CREATE SEQUENCE SEQ_QUESTION START WITH 1;
CREATE SEQUENCE SEQ_OPTION START WITH 1;
CREATE SEQUENCE SEQ_PAPER START WITH 1;
CREATE SEQUENCE SEQ_SESSION START WITH 1;
CREATE SEQUENCE SEQ_AUDIT START WITH 1;

-- 1. 사용자
CREATE TABLE USER_ACCT (
    USER_ID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PWD_HASH VARCHAR2(200) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'STUDENT' CHECK(ROLE IN ('ADMIN','TEACHER','STUDENT')),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 2. 과목
CREATE TABLE SUBJECT (
    SUBJECT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CODE VARCHAR2(20) UNIQUE
);

-- 3. NCS 단원
CREATE TABLE UNIT (
    UNIT_ID NUMBER PRIMARY KEY,
    SUBJECT_ID NUMBER REFERENCES SUBJECT(SUBJECT_ID),
    NCS_CODE VARCHAR2(20),
    NAME VARCHAR2(200) NOT NULL,
    PARENT_ID NUMBER REFERENCES UNIT(UNIT_ID)
);

-- 4. 태그
CREATE TABLE TAG (
    TAG_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) UNIQUE NOT NULL
);

-- 5. 문항
CREATE TABLE QUESTION (
    Q_ID NUMBER PRIMARY KEY,
    UNIT_ID NUMBER REFERENCES UNIT(UNIT_ID),
    EXAM_YEAR NUMBER,
    EXAM_ROUND NUMBER,
    STEM CLOB NOT NULL,
    COMMENTARY CLOB,
    DIFF NUMBER CHECK(DIFF BETWEEN 1 AND 5),
    STATUS VARCHAR2(20) DEFAULT 'APPROVED',
    CREATED_BY NUMBER REFERENCES USER_ACCT(USER_ID),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 6. 선지
CREATE TABLE Q_OPTION (
    OPT_ID NUMBER PRIMARY KEY,
    Q_ID NUMBER REFERENCES QUESTION(Q_ID) ON DELETE CASCADE,
    OPT_NO NUMBER NOT NULL,
    TEXT VARCHAR2(1000) NOT NULL,
    IS_ANSWER CHAR(1) DEFAULT 'N' CHECK(IS_ANSWER IN ('Y','N')),
    UNIQUE(Q_ID, OPT_NO)
);

-- 7. 문항-태그
CREATE TABLE QTAG (
    Q_ID NUMBER REFERENCES QUESTION(Q_ID) ON DELETE CASCADE,
    TAG_ID NUMBER REFERENCES TAG(TAG_ID),
    PRIMARY KEY(Q_ID, TAG_ID)
);

-- 8. 시험지 (기출/맞춤)
CREATE TABLE EXAM_PAPER (
    PAPER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(200) NOT NULL,
    MODE VARCHAR2(10) CHECK(MODE IN ('G','C')),
    EXAM_YEAR NUMBER,
    EXAM_ROUND NUMBER,
    TIME_LIMIT_MIN NUMBER DEFAULT 90,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 9. 시험지-문항
CREATE TABLE PAPER_Q (
    PAPER_ID NUMBER REFERENCES EXAM_PAPER(PAPER_ID) ON DELETE CASCADE,
    Q_ID NUMBER REFERENCES QUESTION(Q_ID),
    ORD NUMBER NOT NULL,
    PRIMARY KEY(PAPER_ID, Q_ID)
);

-- 10. 응시 세션
CREATE TABLE EXAM_SESSION (
    SESS_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER REFERENCES USER_ACCT(USER_ID),
    PAPER_ID NUMBER REFERENCES EXAM_PAPER(PAPER_ID),
    SEED NUMBER NOT NULL,
    START_AT TIMESTAMP NOT NULL,
    END_AT TIMESTAMP NOT NULL,
    SUBMIT_AT TIMESTAMP,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' CHECK(STATUS IN ('ACTIVE','TIMEUP','SUBMIT')),
    SCORE NUMBER,
    RESUME_CNT NUMBER DEFAULT 0
);

-- 11. 응답
CREATE TABLE EXAM_RESP (
    SESS_ID NUMBER REFERENCES EXAM_SESSION(SESS_ID) ON DELETE CASCADE,
    Q_ID NUMBER REFERENCES QUESTION(Q_ID),
    CHOSEN_OPT_NO NUMBER,
    IS_CORRECT CHAR(1),
    ELAPSED_SEC NUMBER,
    FLAG CHAR(1) DEFAULT 'N',
    PRIMARY KEY(SESS_ID, Q_ID)
);

-- 12. 오답노트
CREATE TABLE WRONG_NOTE (
    USER_ID NUMBER REFERENCES USER_ACCT(USER_ID),
    Q_ID NUMBER REFERENCES QUESTION(Q_ID),
    LAST_WRONG_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CNT NUMBER DEFAULT 1,
    PRIMARY KEY(USER_ID, Q_ID)
);

-- 13. 감사 로그
CREATE TABLE AUDIT (
    AUDIT_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    ACTION VARCHAR2(50),
    TARGET VARCHAR2(100),
    IP VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 인덱스
CREATE INDEX IDX_Q_UNIT ON QUESTION(UNIT_ID, STATUS);
CREATE INDEX IDX_Q_YEAR_ROUND ON QUESTION(EXAM_YEAR, EXAM_ROUND);
CREATE INDEX IDX_SESS_USER ON EXAM_SESSION(USER_ID, STATUS);
CREATE INDEX IDX_RESP_SESS ON EXAM_RESP(SESS_ID);
CREATE INDEX IDX_WRONG_USER ON WRONG_NOTE(USER_ID);

-- 샘플 데이터
INSERT INTO SUBJECT VALUES(1, '데이터베이스', 'DB');
INSERT INTO SUBJECT VALUES(2, '프로그래밍언어', 'PL');
INSERT INTO SUBJECT VALUES(3, '소프트웨어공학', 'SE');

INSERT INTO UNIT VALUES(1, 1, 'NCS01', '정규화', NULL);
INSERT INTO UNIT VALUES(2, 1, 'NCS02', 'SQL', NULL);
INSERT INTO UNIT VALUES(3, 2, 'NCS03', '자료구조', NULL);

INSERT INTO TAG VALUES(1, '정규화');
INSERT INTO TAG VALUES(2, 'SQL');
INSERT INTO TAG VALUES(3, '트랜잭션');

-- 관리자 계정 (비밀번호: admin123)
INSERT INTO USER_ACCT VALUES(1, 'admin@test.com', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', '관리자', 'ADMIN', SYSTIMESTAMP);

COMMIT;
